### ISSUE TITLE
Custom Search API also needs to be enabled

### ISSUE THREAD

**Issue by drnic** [Sogody/google-chatgpt-plugin#2]
The plugin was failing for me, I added `print(response.text)` in the `response.status_code == 200` `else` branch and I saw:

` "message": "Custom Search API has not been used in project...` and it included a URL for me to visit to enable Custom Search API.

**Comment by ttomor** [comment]
hi @drnic this plugin does require a Google Custom Search Engine in order to function, in addition to a Google API Key. Links to fetch both the API Key and enable the Custom Search Engine in the links outlined in [Installation (Local)](https://github.com/Sogody/google-chatgpt-plugin#installation-local) section of the README.
